### ISSUE TITLE
Press 1. to FIND LOCATION of an IP 

### ISSUE THREAD

**Issue by bmadhumay** [PriyabrataNaskar/ip-tracker#2]
Press 1. to FIND LOCATION of an IP 
Press 2. to perform REVERSE DNS LOOKUP 
Press 3. to gather Website Information
Press 4. to exit
1
Enter an IP to trace address (e.g:2409:4060:e82:6d43:a1fc:9657:82fe:43e9): 169.254.75.142

###### LOCATION FOR IP 169.254.75.142 TRACKED SUCCESSFULLY ######
Traceback (most recent call last):
  File "C:\Users\Yamac\Documents\GitHub\ip-tracker\eye.py", line 71, in <module>
    driverFunction()
  File "C:\Users\Yamac\Documents\GitHub\ip-tracker\eye.py", line 63, in driverFunction
    findLocation()
  File "C:\Users\Yamac\Documents\GitHub\ip-tracker\eye.py", line 40, in findLocation
    print('Country Code: %s' % (details.country))
  File "C:\Users\Yamac\AppData\Local\Programs\Python\Python39\lib\site-packages\ipinfo\details.py", line 18, in __getattr__
    raise AttributeError(
AttributeError: country is not a valid attribute of Details

**Comment by PriyabrataNaskar** [comment]
```import pprint```

without printing details.country, try with 
```pprint(details)```
